"""Add user_id to responses table

Revision ID: b78dfc951065
Revises: fe38ca70c950
Create Date: 2026-07-27 05:42:14.340096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b78dfc951065'
down_revision = 'fe38ca70c950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("fk_responses_user_id_users", 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses') as batch_op:
        batch_op.drop_constraint("fk_responses_user_id_users", type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
